school_management/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = "St.Paul's school Admin"
admin.site.site_title = "St.Paul's admin portal "
admin.site.index_title = "Welcome to St.Paul's School"


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('user.urls')),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views
from django.views.generic import TemplateView
urlpatterns = [
    path("", views.index,name='home'),
    path("about", views.about,name='about'),
    path("contact", views.contact,name='contact'),
    path("teacher", views.teacher,name='teacher'),
    path("student", views.student,name='student'),
    path("loginteacher",views.loginteacher,name='loginteacher'),
    path("loginstudent",views.loginstudent,name="loginstudent"),
    path('teacher_dashboard',views.teacher_dashboard,name='teacher_dashboard'),
    path('student_dashboard',views.student_dashboard,name='student_dashboard'),
    

    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('password_reset_success/', TemplateView.as_view(template_name="password_reset_success.html"), name='password_reset_success'),
    path('mark1',views.mark1,name='mark1'),
    path('mark2',views.mark2,name='mark2'),
    path('attendance1',views.attendance1,name='attendance1'),
    path('attendance2',views.attendance2,name='attendance2'),
    path('notice1',views.notice1,name='notice1'),
    path('notice_all',views.notice_all,name='notice_all'),
    path('notice_selected',views.notice_selected,name='notice_selected'),
    path('student_marks',views.student_marks,name='student_marks'),
    path('student_attendance',views.student_attendance,name='student_attendance'),
    path('subject_detail',views.subject_detail,name='subject_detail'),
    path('payment2',views.payment2,name='payment2'),

    path('forgot_passwordS/', views.forgot_passwordS, name='forgot_passwordS'),
    path('verify_otpS/', views.verify_otpS, name='verify_otpS'),
    path('reset_passwordS/', views.reset_passwordS, name='reset_passwordS'),
  


]

user/forms.py
# myapp/forms.py

from django import forms
from .models import StudentMarks,StudentAttendance

class EmailForm(forms.Form):
    email = forms.EmailField()

class OTPForm(forms.Form):
    otp = forms.CharField(max_length=6)

class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        

class StudentMarksForm(forms.ModelForm):
    physics = forms.CharField(initial=0,required=False)
    chemistry = forms.CharField(initial=0,required=False)
    class Meta:
        model = StudentMarks
        fields = ('physics', 'chemistry')   

class StudentAttendanceForm(forms.ModelForm):
    attendance_physics=forms.CharField(initial=0,required=False)
    attendance_chemistry=forms.CharField(initial=0,required=False)
    class Meta:
        model=StudentAttendance
        fields=('attendance_physics','attendance_chemistry')

templates/attendance1.html
{% extends "base.html" %}
{% block title %}Enter Class{% endblock title %}
{% block s1 %}

<style>
    .container {
        text-align: center;
        background-color: #ffffff;
        padding: 30px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 100%;
        max-width: 400px;
    }

    p {
        font-size: 1.8em;
        color: rgba(48, 20, 35, 0.8);
        margin-bottom: 20px;
        text-align: center;
        

    }

    form {
        margin:auto;
        background-color: #ffffff;
        padding: 30px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 100%;
        max-width: 400px;
        text-align: center;
        justify-content:center;
        {% comment %} display: inline-block; {% endcomment %}

    }

    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
        color: #007bff;
    }

    input[type="number"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        transition: border-color 0.3s ease;
    }

    input[type="number"]:focus {
        border-color: #007bff;
        outline: none;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #007bff;
        color: white;
        font-size: 1em;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #0056b3;
    }

    button:active {
        background-color: #004080;
    }
</style>


{% endblock s1 %}

{% block body %}

<div class="container">
<p> Hey! {{name}}. which class do you want to give Attendance to : {% for year in classes %}
    {{ year }},
 {% endfor %} </p>

 <form method="POST" action="/attendance1">
    {% csrf_token %}
    <label for="classes">Classes:</label>
    <input type="numder" id="Classes" name="Classes" placeholder="Enter class" required ><br><br>


    <button class="btn btn-primary text-center" type="submit">Submit</button>

</form>
</div>



 
     

{% endblock body %}

templates/attendance2.html
{% extends "base.html" %}
{% block title %}Attendance{% endblock title %}

{% block s1%}
<style>
   

    .container {
      font-family: Arial, sans-serif;
        text-align: center;
        background-color: #ffffff;
        padding: 30px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 100%;
        
        max-width: 800px; /* Adjust width as needed */
    }

    h1 {
        color: #007bff;
        margin-bottom: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    table th, table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }

    table th {
        background-color: #f2f2f2;
        
    }

    input[type="submit"] {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 8px 16px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #0056b3;
    }

    input[type="submit"]:active {
        background-color: #004080;
    }
</style>
{% endblock s1 %}

{% block body %}
<div class="container">
<form method="post">
    {% csrf_token %}
    <h1>Submit Attendance for Class {{ class_id }}</h1>
    <table>
      <thead>
        <tr>
          <th>Student ID</th>
          <th>Student Name</th>
          <th>Attendance in Physics</th>
          <th>Attendance in Chemistry</th>
          <th>Submit</th>
        </tr>
      </thead>
      <tbody>
        {% for student, form in forms %}
        <tr>
          <td>{{ student.student_id }}</td>
          <td>{{ student.name }}</td>
          <td>{{ form.attendance_physics }}</td>
          <td>{{ form.attendance_chemistry }}</td>
          <td><input type="submit" value="Submit" name="submit_{{ student.student_id }}"></td>
         

          {% comment %} <td><input type="submit" value="Submit" name="submit_{{ student.student_id }}"></td> {% endcomment %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </form>
</div>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <style>
      /* styles.css */
    
      
      .navbar {
          background-color: #1f1f1f; /* Dark navbar background */
          padding: 15px 20px;
          position: relative;
          width: 100%;
          top: 0;
          left: 0;
          z-index: 1000;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
      }
      
      .container-nav {
          display: flex;
          justify-content: space-between;
          align-items: center;
          max-width: 1200px;
          margin: 0 auto;
      }
      
      .logo {
          color: #ffcc00; /* Bright logo color */
          font-size: 1.7em;
          text-decoration: none;
          font-weight: bold;
      }
      
      .nav-links {
          list-style: none;
          display: flex;
          margin: 0;
          padding: 0;
      }
      
      .nav-links li {
          margin-left: 20px;
          position: relative; /* For dropdown positioning */
      }
      
      .nav-links a {
          color: #ffffff; /* Light link color */
          text-decoration: none;
          font-size: 1.4em;
          padding: 5px 10px;
          transition: background-color 0.3s ease, color 0.3s ease;
          border-radius: 5px;
      }
      
      .nav-links a:hover {
          background-color: #ffcc00; /* Bright hover background */
          color: #333333; /* Dark text color on hover */
      }
      
      .nav-links a:focus {
          outline: none;
          background-color: #ff9900; /* Different color for focused link */
          color: #ffffff;
      }
      
      /* Dropdown styles */
      .dropdown {
          display: inline-block;
      }
      
      .dropbtn {
          cursor: pointer;
      }
      
      .dropdown-content {
          display: none;
          position: absolute;
          background-color: #333333;
          min-width: 160px;
          box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
          z-index: 1;
          border-radius: 5px;
      }
      
      .dropdown-content a {
          color: #ffffff;
          padding: 10px 15px;
          text-decoration: none;
          display: block;
          transition: background-color 0.3s ease, color 0.3s ease;
          border-radius: 5px;
      }
      
      .dropdown-content a:hover {
          background-color: #ffcc00; /* Bright hover background */
          color: #333333; /* Dark text color on hover */
      }
      
      /* Show the dropdown menu on hover */
      .dropdown:hover .dropdown-content {
          display: block;
      }
      
          
         
          
          

          {% block s1 %}{% endblock s1 %}
    </style>
    <body>
       
      {% if messages %}    
      {% for message in messages %}  
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
        {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}   
      



        
          <nav class="navbar">
            <div class="container-nav">
                <a href="/" class="logo">St. Paul's School</a>
                <ul class="nav-links">
                   
                    <li><a href="about">About Us</a></li>
                    <li><a href="contact">Contact</a></li>
                    <li class="dropdown">
                      <a href="#login" class="dropbtn">Login</a>
                      <div class="dropdown-content">
                          <a href="loginteacher">Login Teacher</a>
                          <a href="loginstudent">Login Student</a>
                      </div>
                  </li>
                  <li><a href="payment2">Pay Fees</a></li>
                </ul>
            </div>
        </nav>

   
    
    {% block body %}{% endblock body %}  
       
       
        
    
    <script> 
      
      {% block script %}
      
      {% endblock script %}
      
    </script>
  </body>
    </html>

templates/forgot_passwordS.html
{% extends "base.html" %}
{% block title %}Forgot Password{% endblock title %}
{% block s1 %}
.container {
  margin-top: 25px;
  text-align: center;
  margin:auto;
  position: relative;
  background-color: #ffffff;
  padding: 30px;
  border: 1px solid #ddd;
  border-radius: 10px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  width: 100%;
  max-width: 500px;
  justify-content:center;
  -ms-transform: translateY(50%);
  transform: translateY(50%);
}

form {
  margin-top: 20px;
}

h2 {
  color: #007bff;
}

p {
  font-size: 1.2em;
  color: #333;
  margin-bottom: 20px;
}

input[type="email"],
button {
  width: 100%;
  padding: 10px;
  margin-bottom: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  transition: border-color 0.3s ease;
}

input[type="email"]:focus {
  border-color: #007bff;
  outline: none;
}

button {
  background-color: #007bff;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

button:hover {
  background-color: #0056b3;
}

button:active {
  background-color: #004080;
}

{% endblock s1 %}


{% block body %}
<!-- myapp/templates/forgot_password.html -->
<div class="container">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send OTP</button>
  </form>


</div>  
  
{% endblock body %}

templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock title %}
{% block s1 %}
/* styles.css */
body, html {
    font-family: 'Arial, sans-serif';
}

.hero-section {
    background: url('static/DSC_0086.jpg') no-repeat center center/cover;
    height: 100vh;
    color: #fff;
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
}

.hero-content {
    background: rgba(0, 0, 0, 0.5);
    padding: 20px;
    border-radius: 10px;
}

.hero-section h1 {
    font-size: 3em;
    margin: 0;
}

.hero-section p {
    font-size: 1.5em;
    margin: 20px 0;
}

.cta-button {
    background-color: #ffcc00;
    color: #333;
    padding: 10px 20px;
    text-decoration: none;
    font-size: 1.2em;
    border-radius: 5px;
    transition: background-color 0.3s ease;
}

.cta-button:hover {
    background-color: #ff9900;
}

.about-us-section {
    padding: 50px 20px;
    background-color: #f4f4f4;
    text-align: center;
}

.about-us-section h2 {
    font-size: 2.5em;
    margin-bottom: 20px;
    color: #333;
}

.about-content {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    max-width: 1200px;
    margin: 0 auto;
}

.about-text {
    flex: 1;
    min-width: 300px;
    margin: 20px;
    color: #555;
    text-align: left;
}

.about-text p {
    margin-bottom: 20px;
    line-height: 1.6;
}

.about-image {
    flex: 1;
    min-width: 300px;
    margin: 20px;
}

.about-image img {
    max-width: 100%;
    height: auto;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

/* styles.css */
/* Footer Section */
.footer {
    background-color: #1f1f1f; /* Dark background color */
    color: #ffffff; /* Light text color */
    padding: 40px 20px;
    text-align: left;
    margin-top: 40px;
}

.container {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    max-width: 1200px;
    margin: 0 auto;
}

.footer-column {
    flex: 1;
    min-width: 200px;
    margin: 20px;
}

.footer-column h3 {
    font-size: 1.5em;
    margin-bottom: 15px;
    color: #ffcc00; /* Bright heading color */
}

.footer-column p,
.footer-column ul {
    margin: 10px 0;
    line-height: 1.6;
}

.footer-column ul {
    list-style: none;
    padding: 0;
}

.footer-column ul li {
    margin-bottom: 10px;
}

.footer-column ul li a {
    color: #ffffff; /* Light link color */
    text-decoration: none;
    transition: color 0.3s ease;
}

.footer-column ul li a:hover {
    color: #ffcc00; /* Bright hover color */
}

.footer-bottom {
    text-align: center;
    margin-top: 20px;
    font-size: 0.9em;
    color: #bbbbbb; /* Light gray color */
}

@media (max-width: 768px) {
    .container {
        flex-direction: column;
        align-items: center;
    }
}

.love_counter {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    background-color: #F5F5F5;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
  
  .counter-Txt {
    width: calc(25% - 20px); /* 25% width with 20px gap */
    margin: 10px;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 10px;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px;
  }
  
  .counter-Txt img {
    width: 64px;
    height: 64px;
    margin-bottom: 10px;
  }
  
  .counter-value {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 10px;
  }
  
  .love_count {
    font-size: 36px;
    font-weight: bold;
    color: #666;
  }
  
  .counter-Txt p {
    font-size: 14px;
    color: #666;
    margin-bottom: 10px;
  }
  
  /* Responsive design */
  @media (max-width: 1200px) {
   .counter-Txt {
      width: calc(33.33% - 20px); /* 33.33% width with 20px gap */
    }
  }
  
  @media (max-width: 992px) {
   .counter-Txt {
      width: calc(50% - 20px); /* 50% width with 20px gap */
    }
  }
  
  @media (max-width: 768px) {
   .counter-Txt {
      width: 100%; /* full width on small screens */
    }
  }
{% endblock s1 %}

{% block body %}
<header class="hero-section">
    <div class="hero-content">
        <h1>Welcome to St. Paul's school</h1>
        <p>Empowering Students for a Brighter Future</p>
        <a href="#about-us" class="cta-button">Learn More</a>
    </div>
</header>

<!-- About Us Section -->
<section id="about-us" class="about-us-section">
    <div class="container">
        <h2>About Us</h2>
        <div class="about-content">
            <div class="about-text">
<p>St. Paul's Senior Secondary School, Shastri Nagar, Jodhpur is one of the many institutions run by the Roman Catholic Diocesan Education Society, Ajmer, in Rajasthan. The school is entrusted to the Diocesan Fathers. It is an English Medium School, which prepares for the All India Secondary School Examination (Class X) and the All India Senior School Certificate Examination (Class XII) of the Central Board of Secondary Education, Delhi.</p>
    <p>This school tries to provide various avenues which would nurture the talents of its students. It gives opportunities for an all-round development of their personality which would eventually bring forth intellectually well developed, emotionally matured and socially committed citizens for India</p>
                <p></p>
            </div>
            <div class="about-image">
                <img src="static/stpaul.jpg" alt="About St. Paul's" height=600px >
            </div>
        </div>
    </div>
</section>


<div class="w-100 ml-0 mt-3" style="background-color:#F5F5F5; min-width:101%">
    <div class="love_counter row justify-content-center w-100" id="counter">
    <div class="col-sm-3 counter-Txt rounded"><img src="static/reading-book.png" alt="/contents/iitbhu/img/icon/reading-book.png" style="filter: grayscale(65%);"><span class="counter-value" data-count="10"> </span>
    <div class="love_count">6495</div>
    <p><span style="font-size:12px; ">Students</span></p></div>
    <div class="col-sm-3 counter-Txt"><img src="static/post_graduate.png" alt="/contents/iitbhu/img/icon/post_graduate.png" style="filter: grayscale(65%);"><span class="counter-value" data-count="25"> </span>
    <div class="love_count">3500+</div>
    <p><span style="font-size:12px;">Students above 95%</span></p></div>
    <div class="col-sm-3 counter-Txt margin-bot-35"><img src="static/female-student.png" alt="/contents/iitbhu/img/icon/female-student.png" style="filter: grayscale(65%);"><span class="counter-value" data-count="25"></span>
    <div class="love_count">1840</div>
    <p><span style="font-size:12px;"> Female Students</span></p></div>
    </div>
    <div class="row love_counter mb-3 justify-content-center w-100" id="counter">
    <div class="col-sm-3 counter-Txt rounded"><img src="static/faculty.png" alt="/contents/iitbhu/img/icon/faculty.png" style="filter: grayscale(65%);" width="64px;"><span class="counter-value" data-count="10"> </span>
    <div class="love_count">348</div>
    <p><span style="font-size:14px;">Faculty</span></p></div>
    </div>
    </div>




<footer class="footer">
    <div class="container">
        <div class="footer-column">
            <h3>Contact Information</h3>
            <p>St. Paul's School</p>
            <p>Sharstri Circle</p>
            <p>Jodhpur, Rajasthan 342001</p>
            <p>Email: info@stpauls.edu</p>
            <p>Phone: +91 935858648</p>
        </div>
        <div class="footer-column">
            <h3>Important Links</h3>
            <ul>
                <li><a href="#privacy-policy">Privacy Policy</a></li>
                <li><a href="#terms-of-service">Terms of Service</a></li>
                <li><a href="#admissions">Admissions</a></li>
                <li><a href="contact">Contact Us</a></li>
            </ul>
        </div>
        <div class="footer-column">
            <h3>Opening Hours</h3>
            <p>Monday - Friday: 8:00 AM - 5:00 PM</p>
            <p>Saturday: 9:00 AM - 1:00 PM</p>
            <p>Sunday: Closed</p>
        </div>
    </div>
    <div class="footer-bottom">
        <p>&copy; 2024 St. Paul's. All Rights Reserved.</p>
    </div>
</footer>

{% endblock body %}

templates/mark1.html
{% extends "base.html" %}
{% block title %}Enter Class{% endblock title %}
{% block s1 %}

<style>
    .container {
        text-align: center;
        background-color: #ffffff;
        padding: 30px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 100%;
        max-width: 400px;
    }

    p {
        font-size: 1.8em;
        color: rgba(48, 20, 35, 0.8);
        margin-bottom: 20px;
        text-align: center;
        

    }

    form {
        margin:auto;
        background-color: #ffffff;
        padding: 30px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 100%;
        max-width: 400px;
        text-align: center;
        justify-content:center;
        {% comment %} display: inline-block; {% endcomment %}

    }

    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
        color: #007bff;
    }

    input[type="number"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        transition: border-color 0.3s ease;
    }

    input[type="number"]:focus {
        border-color: #007bff;
        outline: none;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #007bff;
        color: white;
        font-size: 1em;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #0056b3;
    }

    button:active {
        background-color: #004080;
    }
</style>


{% endblock s1 %}


{% block body %}

<div class="container">
<p> Hey! {{name}}. which class do u want to give marks to : {% for year in classes %}
    {{ year }},
 {% endfor %} </p>

 <form method="POST" action="/mark1">
    {% csrf_token %}
    <label for="classes">Classes:</label>
    <input type="numder" id="Classes" name="Classes" placeholder="Enter class" ><br><br>


    <button class="btn btn-primary text-center" type="submit">Submit</button>

</form>
</div>
 
     

{% endblock body %}

templates/reset_password.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock title %}
{% block s1 %}
.container {
    max-width: 400px;
    margin: 40px auto;
    padding: 20px;
    background-color: #f9f9f9;
    border: 1px solid #ddd;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
  
  /* Header Styles */
  
  h2 {
    margin-top: 0;
    font-weight: bold;
    color: #337ab7;
  }
  
  /* Form Styles */
  
  form {
    margin-top: 20px;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  label {
    display: block;
    margin-bottom: 10px;
    font-weight: bold;
    color: #333;
  }
  
  input[type="password"] {
    width: 100%;
    height: 40px;
    padding: 10px;
    font-size: 16px;
    border: 1px solid #ccc;
    border-radius: 10px;
    transition: border-color 0.3s ease;
  }
  
  input[type="password"]:focus {
    border-color: #337ab7;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
  }
  
  .error {
    color: #red;
    font-size: 14px;
    margin-top: 5px;
  }
  
  /* Button Styles */
  
  button[type="submit"] {
    background-color: #337ab7;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 10px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }
  
  button[type="submit"]:hover {
    background-color: #23527c;
  }
  
  button[type="submit"]:active {
    background-color: #337ab7;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
  }
    

{% endblock s1 %}
{% block body %}
<!-- myapp/templates/reset_password.html -->

<div class="container">
    <h2>Reset Password</h2>
    <form method="post" action="{% url 'reset_password' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            <label for="id_new_password">New Password:</label>
            {{ form.new_password }}
            {% for error in form.new_password.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_confirm_password">Confirm Password:</label>
            {{ form.confirm_password }}
            {% for error in form.confirm_password.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <button type="submit"  class="btn btn-reset">Reset Password</button>
    </form>
</div>
  
{% endblock body %}

templates/student_dashboard.html
{% extends "base.html" %}
{% block title %}Student Dashboard{% endblock title %}
{% block s1 %}
<style>
  body{
  background: url('static/DSC_0086.jpg') no-repeat center center/cover;
  }
  .container-t {
  
    position: relative;
    margin: 10px auto;
    max-width: 800px; /* Adjust the maximum width as needed */
    background-color: rgba(255, 255, 255, 0.8);
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Optional: Add shadow for depth */
    margin-top:150px;
  }

  p {
    font-size: 1.6em;
    text-align: center;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .dashboard-links {
    display: inline-block;
    margin: 10px;
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s ease;
    font-weight: bold;
    margin-left:80px;
  }

  .dashboard-links:hover {
    background-color: #0056b3;
  }

  .dashboard-links:active {
    background-color: #004080;
  }
</style>
{% endblock s1 %}

{% block body %}

<div class="container-t">
<p> Welcome {{name}}!</p> 
<b><a href="student_marks" class="dashboard-links">View Marks</a></b>

<b><a href="student_attendance" class="dashboard-links">View Attendance</a></b>

<b><a href="subject_detail" class="dashboard-links">Subject Details</a></b>

</div>

{% endblock body %}